// Generated by CoffeeScript 1.3.3
(function() {

  ($(document)).ready(function() {
    ($('BUTTON I')).click(function() {
      var res;
      res = ($(this)).hasClass('icon-folder-open');
      ($(this)).removeClass();
      if (res) {
        return ($(this)).addClass('icon-folder-close');
      } else {
        return ($(this)).addClass('icon-folder-open');
      }
    });
    return ($('BUTTON')).click(function() {
      var res;
      res = ($(this)).find('I').hasClass('icon-folder-open');
      ($(this)).find('I').removeClass();
      if (res) {
        return ($(this)).find('I').addClass('icon-folder-close');
      } else {
        return ($(this)).find('I').addClass('icon-folder-open');
      }
    });
  });

}).call(this);
