// Generated by CoffeeScript 1.3.3
(function() {

  ($(document)).ready(function() {
    return ($('BUTTON I')).click(function() {
      return ($(this)).toggleClass('icon-folder-open');
    });
  });

}).call(this);
